os: linux

language: ruby
services:
  - mysql
cache:
  - bundler
env:
  - MYSQL_USERNAME=root MYSQL_PASSWORD=
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
gemfile:
  - .travis/gemfiles/rails5.gemfile
  - .travis/gemfiles/rails5-no-cpk.gemfile
  - .travis/gemfiles/rails6.gemfile
  - .travis/gemfiles/rails6-no-cpk.gemfile
before_install:
  - gem install bundler -v 2.0.2
  - mysql -e 'CREATE DATABASE active_record_upsert_test;'
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: .travis/gemfiles/rails6.gemfile
    - rvm: 2.3.8
      gemfile: .travis/gemfiles/rails6-no-cpk.gemfile
    - rvm: 2.4.9
      gemfile: .travis/gemfiles/rails6.gemfile
    - rvm: 2.4.9
      gemfile: .travis/gemfiles/rails6-no-cpk.gemfile
